from enum import Enum

class Status(Enum):
    SUCCESS = 'SUCCESS'
    FILLED = 'FILLED'
    NOT_FOUND = 'NOT_FOUND'
    UNAUTHORIZED = 'UNAUTHORIZED'

class AuthStatus(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    INVALID_TOKEN = 'INVALID_TOKEN'
    INVALID_USER = 'INVALID_USER'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    INVALID_EMAIL = 'INVALID_EMAIL'
    INVALID_USERNAME = 'INVALID_USERNAME'
    INVALID_ROLE = 'INVALID_ROLE'
    INVALID_STATUS = 'INVALID_STATUS'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD'
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    FORBIDDEN = 'FORBIDDEN'

class Roles(Enum):
    ADMIN = 'ADMIN'
    USER = 'USER'

class OrderStatus(Enum):
    PENDING = 'PENDING'
    PROCCESING = 'PROCCESING'
    COMPLETED = 'COMPLETED'
    REJECTED = 'REJECTED'

class HouseStatus(Enum):
    CONSTRUCT = 'CONSTRUCT'
    CONSTRUCT_FOR_ORDER = 'CONSTRUCT_FOR_ORDER'
    FOR_SALE = 'FOR_SALE'
    SOLD = 'SOLD'

class ApartmentParametersStatus(Enum):
    NO_BALCONY = "NO"
    ONE_BALCONY = "1"
    TWO_BALCONY = "2"
    SEPARATE_BATHROOM = "SEPARATE"
    COMBINED_BATHROOM = "COMBINED"

class HouseAdditionsStatus(Enum):
    PARCKING_YES = "YES"
    PARCKING_NO = "NO"
    PLAYGROUND_YES = "YES"
    PLAYGROUND_NO = "NO"
    BASEMENT_YES = "YES"
    BASEMENT_NO = "NO"
    GREEN_ZONE_YES = "YES"
    GREEN_ZONE_NO = "NO"
    CARGO_ELEVATOR = "CARGO"
    PASSENGER_ELEVATOR = "PASSENGER"
    


