"""empty message

Revision ID: 7ebb3732d544
Revises: 
Create Date: 2025-05-16 22:36:42.110190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebb3732d544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('main_image', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('is_order', sa.Boolean(), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('entrances', sa.Integer(), nullable=False),
    sa.Column('begin_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('start_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('area', sa.DECIMAL(), nullable=False),
    sa.Column('id_house', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['apartment_category.id'], ),
    sa.ForeignKeyConstraint(['id_house'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_attributes',
    sa.Column('id_house', sa.Integer(), nullable=False),
    sa.Column('id_attribute', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_attribute'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['id_house'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id_house', 'id_attribute')
    )
    op.create_table('house_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_house', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_house'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_house', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('contract_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('create_date', sa.DATE(), nullable=False),
    sa.Column('update_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_house'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartment_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('id_apartment', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_apartment'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apartments_parameters',
    sa.Column('id_apartment', sa.Integer(), nullable=False),
    sa.Column('id_parameter', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_apartment'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['id_parameter'], ['parameters.id'], ),
    sa.PrimaryKeyConstraint('id_apartment', 'id_parameter')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments_parameters')
    op.drop_table('apartment_images')
    op.drop_table('orders')
    op.drop_table('house_images')
    op.drop_table('house_attributes')
    op.drop_table('apartments')
    op.drop_table('users')
    op.drop_table('parameters')
    op.drop_table('houses')
    op.drop_table('attributes')
    op.drop_table('apartment_category')
    # ### end Alembic commands ###
