"""empty message

Revision ID: d785ff31686d
Revises: f44675e01b5a
Create Date: 2025-05-17 18:09:21.732047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd785ff31686d'
down_revision: Union[str, None] = 'f44675e01b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_date', sa.DATE(), nullable=True))
    op.add_column('orders', sa.Column('sign_off_date', sa.DATE(), nullable=True))
    op.add_column('orders', sa.Column('completion_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completion_date')
    op.drop_column('orders', 'sign_off_date')
    op.drop_column('orders', 'payment_date')
    # ### end Alembic commands ###
