"""empty message

Revision ID: fed1e95994cc
Revises: 08ee3e85bb3d
Create Date: 2025-05-17 16:13:33.520877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed1e95994cc'
down_revision: Union[str, None] = '08ee3e85bb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('main_image', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'main_image')
    # ### end Alembic commands ###
